### ISSUE TITLE
Word to InDesign (tabulation)

### ISSUE THREAD

**Issue by Indigrep** [RolandDreger/indesign-word-import#15]
Hello Romand,
I hope you are well. I have recently tested the last version of the script, and it works perfectly (I appreciate the option to minimize character styles). Just to inform you, there is something strange when I import **directly** a document, first exported from InDesign to Word with the plugin WordsFlow : see the screenshot below. Every think is OK when I save as the file.
![import_doc](https://user-images.githubusercontent.com/105438401/190918385-46eedab0-3cc2-4d90-8296-523250464526.png)
Best
Laurent

**Comment by RolandDreger** [comment]
Hello Laurent,

thank you for the information. I have also noticed that Word documents exported via WordsFlow can have a slightly different (internal) structure. If you want, I can take a look at it. (You can send me the document by email, if you are not allowed to publish it here).

With "Save as" in Word this was fixed, as far as I remember. Could be WordsFlow is creating an old or not quite correct document structure here and Word is fixing it then!?

Greetings
Roland

**Comment by RolandDreger** [comment]
The very, very late and simple answer to this issue: WordsFlow stores the XML structure with indents in the file. 

I could adapt the transformation to this, but this would then collide with my concept, namely to transfer all content (even in unforeseen situations) from the Word document into the InDesign document or also reduce the performance.

No idea if you can make a setting for this in WordsFlow. Another possibility would be to remove the tabs in InDesign with a script.

**Comment by Indigrep** [comment]
Thank you for your response. In the end, someone who uses WordFlow will only use it! There is no need to adapt your script.
