### ISSUE TITLE
Get list type in indesign

### ISSUE THREAD

**Issue by davidmaissen** [RolandDreger/indesign-word-import#17]
Hi,
thx for this amazing script. is there any plan to map the list type in indesign (e.g. as an XML attribute)? This would be especially helpful for documents without a clean formatting structure.

**Comment by RolandDreger** [comment]
Hi,

that's a good idea, an attribute whether it's an ordered or unordered list, with bullet or decimal. That's what you mean, right? 

Regarding lists, another improvement is also planned, that can be implemented together.

**Comment by davidmaissen** [comment]
yes, that's exactly what i mean. i'm looking forward to seeing the improvement regarding lists. thanks a lot.

**Comment by RolandDreger** [comment]
So, finally found the time to address the issue. New attributes for the list items: `list-format` and `list-start`. Both values belong for the whole list.

**`list-format`**

Possible values are, for example: `decimal`, `lowerRoman`, `bullet`, `cardinalText`, `custom; 001, 002, 003, ...`, ...

**`list-start`**

<img width="566" alt="Bildschirmfoto 2023-04-01 um 17 13 46" src="https://user-images.githubusercontent.com/19747449/229344348-a64ff783-1e0a-4ee4-ad63-8636a9c8d588.png">
<img width="529" alt="Bildschirmfoto 2023-04-01 um 17 15 44" src="https://user-images.githubusercontent.com/19747449/229344349-aba7b3a9-e36e-46bd-a314-9076970add58.png">
<img width="598" alt="Bildschirmfoto 2023-04-01 um 17 20 46" src="https://user-images.githubusercontent.com/19747449/229344350-05731463-e880-4040-8c45-a70290c5fddf.png">

The Word and InDesign lists are organized slightly differently, so they can't be mapped 1:1. But hopefully the attributes will help to reproduce the lists in InDesign.
